### ISSUE TITLE
Complete code 

### ISSUE THREAD

**Issue by yh2424** [YKgroup-HYU/LPN_vs_VPN_pub#2]
Draw circuit as below
![image](https://user-images.githubusercontent.com/32427749/93833782-973ea780-fcb4-11ea-80bf-9ee9dacc323c.png)

- Use this [package](https://schemdraw.readthedocs.io/en/latest/index.html)
- Code `src/draw_circuit.py`

**Comment by New-TW** [comment]
![Figure_1](https://user-images.githubusercontent.com/70870983/94000638-6785c180-fdd2-11ea-8db0-e16b8629f9ae.png)

만들어 봤습니다!

**Comment by New-TW** [comment]
![Figure_1](https://user-images.githubusercontent.com/70870983/94000790-9e5bd780-fdd2-11ea-81e2-e4fcc12c960b.png)
만들었습니다!

**Comment by New-TW** [comment]
교수님 PUSH 단계에서 다음과 같은 error가 뜹니다

remote: Permission to YKgroup-HYU/LPN_vs_VPN_pub.git denied to New-TW.

fatal: unable to access 'https://github.com/YKgroup-HYU/LPN_vs_VPN_pub/': The requested URL returned error: 403

이미 repo에 참여해있는데 왜 권한이 없다는지 모르겠습니다..

**Comment by yh2424** [comment]
음...
먼저 
Main repo `https://github.com/YKgroup-HYU/LPN_vs_VPN_pub` 를 folk 하시고,
folk 한 repo 에 push 하시고,
Main repo 에 Pull request 하는 거랍니다. 

해보시고, 잘 안되면 내일 미팅때 알려줄께요!

**Comment by yh2424** [comment]
Solved 
Pull request #3
